#!/usr/bin/env php
<?php

define('SPARKED', true);

// Ruta al controlador frontal
define('FCPATH', __DIR__ . DIRECTORY_SEPARATOR . 'public' . DIRECTORY_SEPARATOR);

chdir(FCPATH);

// Cargar configuración de rutas
require FCPATH . '../app/Config/Paths.php';

$paths = new Config\Paths();

// Cargar arranque del framework
require $paths->systemDirectory . '/Boot.php';

exit(CodeIgniter\Boot::bootSpark($paths));